'''
    For QQ智慧校园
    Provides the encapsulation two times of the QQ OAuth2 APIs

    Coding By Niangliang
    Generated By Niang on 2017-08-11 20:06:47.356191
    '''
import json
import ssl
from importlib import import_module
from . import settings

try:
    from urllib import parse, request
except ImportError:
    import urlparse as parse
    import urllib2 as request

if settings.FLASK_ON and settings.DJANGO_ON:
    raise ImportError("Two options can not be both True")
elif not settings.FLASK_ON and not settings.DJANGO_ON:
    raise ImportError("Two options can not be both False")


class OAuthQQ(object):
    context = ssl._create_unverified_context()

    def __init__(self, appid, appkey, redirect_uri):
        '''
        构造函数
        :param appid: 校园号唯一标识
        :param appkey: 校园号唯一凭证秘钥
        :param redirect_uri: 回调地址
        '''
        self.appid = appid
        self.appkey = appkey
        self.redirect_uri = redirect_uri

    def get_access_token(self):
        try:
            Accesstoken = import_module(settings.AccesstokenModel).Accesstoken
        except ImportError:
            raise ImportError("You should setting the AccessToken Model router in setting.py")
