# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import operation.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_list', to='business.Business', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家订单列表',
                'verbose_name_plural': '商家订单列表',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.Food', validators=[operation.models.business_is_open_validator], verbose_name='订单食物'),
        ),
        migrations.AddField(
            model_name='businessorderlist',
            name='orders',
            field=models.ManyToManyField(to='operation.Order', verbose_name='订单'),
        ),
    ]
