# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usercollect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercollect',
            options={'verbose_name': '用户收藏', 'verbose_name_plural': '用户收藏'},
        ),
    ]
