# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20170809_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_done'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
    ]
