# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20170819_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prank',
            field=models.IntegerField(default=0, verbose_name='价格评分'),
        ),
        migrations.AddField(
            model_name='order',
            name='trank',
            field=models.IntegerField(default=0, verbose_name='口味评分'),
        ),
    ]
