# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20170822_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
