# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-22 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20170822_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesstextcomment',
            name='business',
        ),
        migrations.DeleteModel(
            name='BusinessTextComment',
        ),
    ]
