# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20170917_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_pickup',
            field=models.CharField(default=1, max_length=10, verbose_name='取餐时间'),
            preserve_default=False,
        ),
    ]
