# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_order_date_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='备注'),
        ),
    ]
