# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_order_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_pickup',
            field=models.CharField(max_length=15, verbose_name='取餐时间'),
        ),
    ]
