# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商家名称')),
                ('position', models.IntegerField(choices=[(1, '楚原食堂'), (2, '汉源食堂')], db_index=True, verbose_name='位置')),
                ('floor', models.IntegerField(choices=[(1, '一楼'), (2, '二楼')], verbose_name='楼层')),
                ('type', models.IntegerField(choices=[(1, '餐品'), (2, '饮品')], db_index=True, verbose_name='商家类型')),
                ('image', models.ImageField(blank=True, storage=storage.storage.ImgStorage(), upload_to='bimg/%Y/%m/%d', verbose_name='商家图片')),
                ('average', models.IntegerField(default=10, verbose_name='人均消费')),
                ('num_like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_open', models.BooleanField(default=False, verbose_name='是否接受预约')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名')),
                ('image', models.ImageField(blank=True, null=True, storage=storage.storage.ImgStorage(), upload_to='fimg/%Y/%m/%d', verbose_name='商品图片')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('can_reserve', models.BooleanField(default=True, verbose_name='可否预约')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodlist', to='business.Business', verbose_name='商家')),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物',
            },
        ),
    ]
