# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='can_reserve',
            field=models.BooleanField(default=False, verbose_name='可否预约'),
        ),
    ]
