# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='商品名')),
                ('image', models.ImageField(blank=True, storage=storage.storage.ImgStorage(), upload_to='fimg/%Y/%m/%d', verbose_name='商品图片')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('can_reservex', models.BooleanField(default=True, verbose_name='可否预约')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodlist', to='business.Business', verbose_name='商品')),
            ],
            options={
                'verbose_name': '食物',
                'verbose_name_plural': '食物',
            },
        ),
    ]
