# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-19 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='综合评价'),
        ),
    ]
