# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='can_reservex',
            new_name='can_reserve',
        ),
        migrations.AlterField(
            model_name='food',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodlist', to='business.Business', verbose_name='商家'),
        ),
    ]
