# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170809_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家')),
                ('food', models.ManyToManyField(to='business.Food', verbose_name='食物')),
            ],
            options={
                'verbose_name': '特色菜',
                'verbose_name_plural': '特色菜',
            },
        ),
    ]
