# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special',
            old_name='food',
            new_name='foods',
        ),
        migrations.AlterField(
            model_name='special',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special', to='business.Business', verbose_name='商家'),
        ),
    ]
