# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20170808_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storage.storage.ImgStorage(), upload_to='fimg/%Y/%m/%d', verbose_name='商品图片'),
        ),
    ]
