# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_business_sort_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='position',
            field=models.IntegerField(choices=[(1, '楚园食堂'), (2, '汉园食堂'), (3, '校内商家')], db_index=True, verbose_name='位置'),
        ),
    ]
