# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20170808_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, '餐品'), (2, '饮品')], default=1, verbose_name='商家类型'),
            preserve_default=False,
        ),
    ]
