# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_auto_20171022_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='floor',
            field=models.IntegerField(choices=[(1, '一楼'), (2, '二楼'), (3, '竹枫斋楼下')], verbose_name='楼层'),
        ),
    ]
