# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170808_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='position',
            field=models.IntegerField(choices=[(1, '楚原食堂'), (2, '汉源食堂')], db_index=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='business',
            name='type',
            field=models.IntegerField(choices=[(1, '餐品'), (2, '饮品')], db_index=True, verbose_name='商家类型'),
        ),
    ]
