# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170810_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/base_avatar.png', storage=storage.storage.ImgStorage(), upload_to='avatar/%Y/%m/%d', verbose_name='头像'),
        ),
    ]
