# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170823_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banday',
            field=models.IntegerField(default=0, verbose_name='封禁天数'),
        ),
    ]
