# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-24 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_banday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_ban',
            field=models.DateTimeField(blank=True, null=True, verbose_name='开始封禁的时间'),
        ),
    ]
