# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170810_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthqqprofile',
            options={'verbose_name': 'QQ个人信息', 'verbose_name_plural': 'QQ个人信息'},
        ),
    ]
