# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170810_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqqprofile',
            name='stuid',
            field=models.CharField(blank=True, max_length=20, verbose_name='学号'),
        ),
    ]
