# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170810_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesstoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
