# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-10 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170810_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phonenumber',
        ),
    ]
