# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_user_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, default='/media/avatar/base_avatar.png', verbose_name='头像'),
        ),
    ]
