# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170811_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(choices=[(0, '商家'), (1, '用户')], default=0, verbose_name='用户类型'),
        ),
    ]
