# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20170811_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, verbose_name='头像'),
        ),
    ]
