# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170811_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authapply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商家名称')),
                ('position', models.IntegerField(choices=[(1, '楚原食堂'), (2, '汉源食堂')], verbose_name='位置')),
                ('floor', models.IntegerField(choices=[(1, '一楼'), (2, '二楼')], verbose_name='楼层')),
                ('type', models.IntegerField(choices=[(1, '餐品'), (2, '饮品')], verbose_name='商家类型')),
            ],
            options={
                'verbose_name': '商家认证申请',
                'verbose_name_plural': '商家认证申请',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, verbose_name='联系方式'),
        ),
        migrations.AddField(
            model_name='user',
            name='truename',
            field=models.CharField(blank=True, max_length=30, verbose_name='真实姓名'),
        ),
    ]
