# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20170812_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='authapply',
            name='date_apply',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='申请时间'),
            preserve_default=False,
        ),
    ]
