# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_authapply_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authapply',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='是否通过'),
        ),
        migrations.AlterField(
            model_name='authapply',
            name='position',
            field=models.IntegerField(choices=[(1, '楚园食堂'), (2, '汉园食堂')], verbose_name='位置'),
        ),
    ]
