# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_auto_20170808_1129'),
        ('sdiningview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Business', verbose_name='商家')),
            ],
            options={
                'verbose_name': '推荐商家',
                'verbose_name_plural': '推荐商家',
            },
        ),
    ]
